stages:
  load_data:
    cmd: python stage_01_load_save.py --config=config/config.yaml
    deps:
      - stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml 
    outs:
      - data/cat
      - data/dog